#ifndef CONFIG_H
#define CONFIG_H

/*
    config.h - DO NOT EDIT THIS FILE, change what you need in config_override.h
    See config_override_example.h
*/
#define USE_CONFIG_OVERRIDE

// OPTIONAL: Assign default values here.
#define WIFI_SSID "" // Leave unset for wireless autoconfig. Note that these values will be lost
#define WIFI_PASS "" // when updating, but that's probably OK because they will be saved in EEPROM.

////////////////////////////////////////////////////////////////////////////////////////////////////
// These defaults may be overwritten with values saved by the web interface
#define MQTT_SRV ""
#define MQTT_PORT 1883
#define MQTT_USER ""
#define MQTT_PASS ""
#define MQTT_MAX_PACKET_SIZE 4096

#define HASP_NODE "plate01"
#define GROUP_NAME "plates"
#define WEB_USER "admin"
#define WEB_PASS ""
#define MOTION_PIN 0

#define WIFI_CONFIG_SSID "hasplate"      // First-time config WPA2 password
#define WIFI_CONFIG_PASS "HASwitchPlate" // First-time config SSID

// Additional CSS style to match Hass theme
#define HASP_STYLE_STRING "<style>button{background-color:#03A9F4;}body{width:60%;margin:auto;}input:invalid{border:1px solid red;}input[type=checkbox]{width:20px;}</style>"

// Default link to compiled Arduino firmware image
#define ESP_FIRMWARE_URL "http://haswitchplate.com/update/HASwitchPlate.ino.d1_mini.bin"
// Default link to compiled Nextion firmware images
#define LCD_FIRMWARE_URL "http://haswitchplate.com/update/HASwitchPlate.tft"

#ifdef USE_CONFIG_OVERRIDE
#include <config_override.h> // Configuration overrides
#endif

#endif